// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class AppPriv
    {
        public AppPriv()
        {
            AppRoleMenus = new HashSet<AppRoleMenu>();
        }

        public int AppPrivId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<AppRoleMenu> AppRoleMenus { get; set; }
    }
}