// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class AppRoleMenu
    {
        public int AppRoleMenuId { get; set; }
        public Guid RoleId { get; set; }
        public int AppSubMenuId { get; set; }
        public int AppPrivId { get; set; }
        public bool? CanAdd { get; set; }
        public bool? CanEdit { get; set; }
        public bool? CanDelete { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual AppPriv AppPriv { get; set; }
        public virtual AppSubMenu AppSubMenu { get; set; }
        public virtual Role Role { get; set; }
    }
}