// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class AppSubMenu
    {
        public AppSubMenu()
        {
            AppRoleMenus = new HashSet<AppRoleMenu>();
            CostCenterSubMenus = new HashSet<CostCenterSubMenu>();
        }

        public int AppSubMenuId { get; set; }
        public int AppMainMenuId { get; set; }
        public string NavUrl { get; set; }
        public string MenuText { get; set; }
        public int? OrderId { get; set; }
        public bool? IsShow { get; set; }
        public bool? HasWorkflow { get; set; }
        public bool? IsDeleted { get; set; }
        public bool? IsCostCenterSpecific { get; set; }
        public string AlternateMenuText { get; set; }

        public virtual AppMainMenu AppMainMenu { get; set; }
        public virtual ICollection<AppRoleMenu> AppRoleMenus { get; set; }
        public virtual ICollection<CostCenterSubMenu> CostCenterSubMenus { get; set; }
    }
}