// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class ClientResponseDatum
    {
        public int ClientResponseId { get; set; }
        public string EngagementCode { get; set; }
        public string Response { get; set; }
        public string ResponseEmailAddress { get; set; }
        public DateTime DateOfResponse { get; set; }
        public string UploadedBy { get; set; }
        public DateTime? UploadedDate { get; set; }
    }
}