// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class CostCenter
    {
        public CostCenter()
        {
            CostCenterSubMenus = new HashSet<CostCenterSubMenu>();
        }

        public int CostCenterId { get; set; }
        public string Name { get; set; }
        public bool? IsDeleted { get; set; }

        public virtual ICollection<CostCenterSubMenu> CostCenterSubMenus { get; set; }
    }
}