// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class CredProjectRestrictedReason
    {
        public int RestrictedReasonId { get; set; }
        public Guid ProjectId { get; set; }
        public int ReasonId { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }

        public virtual Project Project { get; set; }
        public virtual Taxonomy Reason { get; set; }
    }
}