// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class DataDump
    {
        public string ProjectCode { get; set; }
        public string TaskCode { get; set; }
        public string ClientName { get; set; }
        public string ClienteMail { get; set; }
        public string ProjectPartner { get; set; }
        public string TaskManager { get; set; }
        public string HoursBooked { get; set; }
        public string BillingAmount { get; set; }
        public string Sbu { get; set; }
        public string LegalEntity { get; set; }
        public string ProjectName { get; set; }
        public string EngagementType { get; set; }
        public string TargetEntityName { get; set; }
        public string BusinessDescription { get; set; }
        public string ShortDescription { get; set; }
        public string CompletedOn { get; set; }
        public string WebsiteUrl { get; set; }
        public string QuotedinAnnouncements { get; set; }
        public string NatureofEngagement { get; set; }
        public string DealType { get; set; }
        public string DealValue { get; set; }
        public string SubSector { get; set; }
        public string Services { get; set; }
        public string TransactionStatus { get; set; }
        public string ClientEntityType { get; set; }
        public string DomicileCountryRegion { get; set; }
        public string WorkCountryRegion { get; set; }
        public string EntityNameDisclosed { get; set; }
        public string TargetEntityType { get; set; }
        public int? SbuId { get; set; }
        public int? LegalEntityId { get; set; }
        public Guid? ProjectId { get; set; }
        public int? EngagementTypeId { get; set; }
        public int? NatureofEngagementId { get; set; }
        public int? DealTypeId { get; set; }
        public int? DealValueId { get; set; }
        public int? SubSectorId { get; set; }
        public int? ServiceId { get; set; }
        public int? TransactionStatusId { get; set; }
        public int? ClientEntityTypeId { get; set; }
        public int? DomicileCountryRegionId { get; set; }
        public int? EntityNameDisclosedId { get; set; }
        public int? WorkCountryRegionId { get; set; }
        public int? TargetEntityTypeId { get; set; }
    }
}