// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class DisputeRequest
    {
        public DisputeRequest()
        {
            ProjectCtmDetailDuplicateDisputeRequests = new HashSet<ProjectCtmDetail>();
            ProjectCtmDetailErrorDisputeRequests = new HashSet<ProjectCtmDetail>();
        }

        public Guid DisputeRequestId { get; set; }
        public Guid? CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public decimal? DisputeNumber { get; set; }
        public string DisputeNotes { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual ICollection<ProjectCtmDetail> ProjectCtmDetailDuplicateDisputeRequests { get; set; }
        public virtual ICollection<ProjectCtmDetail> ProjectCtmDetailErrorDisputeRequests { get; set; }
    }
}