// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class EmailReminder
    {
        public Guid ReminderId { get; set; }
        public int? NoOfDays { get; set; }
        public Guid EmailTemplateId { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? ReminderOrder { get; set; }

        public virtual MailTemplate EmailTemplate { get; set; }
    }
}