// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class InputSearchTrackDetail
    {
        public int InputSearchTrackDetailsId { get; set; }
        public string UserId { get; set; }
        public string JsonDataContent { get; set; }
        public string SearchCategoryType { get; set; }
        public DateTime? CreatedOn { get; set; }
    }
}