// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class JobLog
    {
        public Guid JobLogId { get; set; }
        public Guid? EmailTemplateId { get; set; }
        public DateTime? ExecutedOn { get; set; }

        public virtual MailTemplate EmailTemplate { get; set; }
    }
}