// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class MailQueue
    {
        public int MailQueueId { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTo { get; set; }
        public string EmailCc { get; set; }
        public string EmailBcc { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? LastRetry { get; set; }
        public int MailStatusTypeId { get; set; }
        public string AttachedFilePaths { get; set; }
        public Guid? CreatedBy { get; set; }

        public virtual MailStatusType MailStatusType { get; set; }
    }
}