// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class MailStatusType
    {
        public MailStatusType()
        {
            MailQueues = new HashSet<MailQueue>();
        }

        public int MailStatusTypeId { get; set; }
        public string Name { get; set; }

        public virtual ICollection<MailQueue> MailQueues { get; set; }
    }
}