// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class MailTemplate
    {
        public MailTemplate()
        {
            EmailReminders = new HashSet<EmailReminder>();
            JobLogs = new HashSet<JobLog>();
            ProjectMailDetails = new HashSet<ProjectMailDetail>();
        }

        public string TemplateName { get; set; }
        public string MailTemplate1 { get; set; }
        public Guid MailTemplateId { get; set; }
        public string StageType { get; set; }
        public string EmailTo { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public string EmailCc { get; set; }
        public string EmailBcc { get; set; }
        public string Email { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }

        public virtual ICollection<EmailReminder> EmailReminders { get; set; }
        public virtual ICollection<JobLog> JobLogs { get; set; }
        public virtual ICollection<ProjectMailDetail> ProjectMailDetails { get; set; }
    }
}