// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class ProjectWfNextAction
    {
        public int ProjectWfNextActionId { get; set; }
        public int ProjectWfStatusTypeId { get; set; }
        public int ProjectWfActionId { get; set; }

        public virtual ProjectWfAction ProjectWfAction { get; set; }
        public virtual ProjectWfStatusType ProjectWfStatusType { get; set; }
    }
}