// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class ProjectMailDetail
    {
        public Guid ProjectId { get; set; }
        public Guid EmailTemplateId { get; set; }
        public DateTime? SendDate { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public Guid ProjectEmailId { get; set; }

        public virtual MailTemplate EmailTemplate { get; set; }
        public virtual Project Project { get; set; }
    }
}