// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class ProjectWfUserTypeAction
    {
        public int ProjectWfUserTypeActionId { get; set; }
        public int UserTypeId { get; set; }
        public int ProjectWfActionId { get; set; }
    }
}