// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class ProjectWfLog
    {
        public int ProjectWflogId { get; set; }
        public int ProjectWfActionId { get; set; }
        public int ProjectWfStatustypeId { get; set; }
        public DateTime CreatedOn { get; set; }
        public Guid ProjectId { get; set; }
        public Guid CreatedBy { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual Project Project { get; set; }
        public virtual ProjectWfAction ProjectWfAction { get; set; }
        public virtual ProjectWfStatusType ProjectWfStatustype { get; set; }
    }
}