// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class Project
    {
        public Project()
        {
            CredProjectRestrictedReasons = new HashSet<CredProjectRestrictedReason>();
            ProjectCredLookups = new HashSet<ProjectCredLookup>();
            ProjectCtmDetails = new HashSet<ProjectCtmDetail>();
            ProjectCtmLookups = new HashSet<ProjectCtmLookup>();
            ProjectMailDetails = new HashSet<ProjectMailDetail>();
            ProjectPublicWebsites = new HashSet<ProjectPublicWebsite>();
            ProjectWfLogs = new HashSet<ProjectWfLog>();
        }

        public string ProjectCode { get; set; }
        public string TaskCode { get; set; }
        public string ClientName { get; set; }
        public string ClienteMail { get; set; }
        public string ProjectPartner { get; set; }
        public string TaskManager { get; set; }
        public decimal? HoursBooked { get; set; }
        public DateTime? UploadedDate { get; set; }
        public decimal? BillingAmount { get; set; }
        public int? ProjectStatusId { get; set; }
        public int ProjectTypeId { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Guid ProjectId { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? ModifieddBy { get; set; }
        public int? SbuId { get; set; }
        public int? LegalEntityId { get; set; }
        public string Name { get; set; }
        public string ClientContactName { get; set; }
        public int? ProjectCtmstatusId { get; set; }
        public int? ProjectValuationStatusId { get; set; }
        public bool? Canactive { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? LTB { get; set; }
        public string Debtor { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual Taxonomy LegalEntity { get; set; }
        public virtual User ModifieddByNavigation { get; set; }
        public virtual ProjectWfStatusType ProjectStatus { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual Taxonomy Sbu { get; set; }
        public virtual ProjectCredDetail ProjectCredDetail { get; set; }
        public virtual ICollection<CredProjectRestrictedReason> CredProjectRestrictedReasons { get; set; }
        public virtual ICollection<ProjectCredLookup> ProjectCredLookups { get; set; }
        public virtual ICollection<ProjectCtmDetail> ProjectCtmDetails { get; set; }
        public virtual ICollection<ProjectCtmLookup> ProjectCtmLookups { get; set; }
        public virtual ICollection<ProjectMailDetail> ProjectMailDetails { get; set; }
        public virtual ICollection<ProjectPublicWebsite> ProjectPublicWebsites { get; set; }
        public virtual ICollection<ProjectWfLog> ProjectWfLogs { get; set; }
    }
}