// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class ProjectsAuditLog
    {
        public Guid Uid { get; set; }
        public Guid Projectid { get; set; }
        public string OldRowData { get; set; }
        public string NewRowData { get; set; }
        public DateTime DmlTimestamp { get; set; }
        public string DmlCreatedBy { get; set; }
        public string ModificationType { get; set; }
        public bool? IsModified { get; set; }
        public string SrcTableName { get; set; }
        public string DmlType { get; set; }
    }
}