// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class ProjectWfStatusType
    {
        public ProjectWfStatusType()
        {
            ProjectCtmDetailDuplicateWfStatuses = new HashSet<ProjectCtmDetail>();
            ProjectCtmDetailErrorDataWfStatuses = new HashSet<ProjectCtmDetail>();
            ProjectWfLogs = new HashSet<ProjectWfLog>();
            ProjectWfNextActions = new HashSet<ProjectWfNextAction>();
            Projects = new HashSet<Project>();
        }

        public int ProjectWfStatusTypeId { get; set; }
        public string Name { get; set; }
        public string DashboardIcon { get; set; }
        public int? DashboardOrder { get; set; }
        public int ProjectTypeId { get; set; }
        public int? WfOrderId { get; set; }

        public virtual ICollection<ProjectCtmDetail> ProjectCtmDetailDuplicateWfStatuses { get; set; }
        public virtual ICollection<ProjectCtmDetail> ProjectCtmDetailErrorDataWfStatuses { get; set; }
        public virtual ICollection<ProjectWfLog> ProjectWfLogs { get; set; }
        public virtual ICollection<ProjectWfNextAction> ProjectWfNextActions { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}