// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class ProjectCtmDetail
    {
        public Guid ProjectId { get; set; }
        public DateOnly? TransactionDate { get; set; }
        public string TargetName { get; set; }
        public string TargetBusinessDescription { get; set; }
        public string BidderName { get; set; }
        public decimal? StakeAcquired { get; set; }
        public decimal? DealValue { get; set; }
        public decimal? EnterpriseValue { get; set; }
        public decimal? Revenue { get; set; }
        public decimal? Ebitda { get; set; }
        public decimal? EvRevenue { get; set; }
        public decimal? EvEbitda { get; set; }
        public Guid CreatedBy { get; set; }
        public DateTime CreatedOn { get; set; }
        public Guid? ModifiedBy { get; set; }
        public DateTimeOffset? ModifiedOn { get; set; }
        public long ProjectCtmId { get; set; }
        public int? CtmDealTypeId { get; set; }
        public int? SourceOfMultipleId { get; set; }
        public int? CurrencyId { get; set; }
        public int? TargetListedTypeId { get; set; }
        public decimal? CustomMultile { get; set; }
        public string NameOfMultiple { get; set; }
        public int? DuplicateWfStatusId { get; set; }
        public int? ErrorDataWfStatusId { get; set; }
        public string Notes { get; set; }
        public Guid? DuplicateDisputeRequestId { get; set; }
        public string ErrorNotes { get; set; }
        public string KeyWords { get; set; }
        public Guid? ErrorDisputeRequestId { get; set; }
        public int? CtmControllingTypeId { get; set; }
        public DateTime? DisputeUpdatedOn { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual Taxonomy CtmControllingType { get; set; }
        public virtual Taxonomy CtmDealType { get; set; }
        public virtual Taxonomy Currency { get; set; }
        public virtual DisputeRequest DuplicateDisputeRequest { get; set; }
        public virtual ProjectWfStatusType DuplicateWfStatus { get; set; }
        public virtual ProjectWfStatusType ErrorDataWfStatus { get; set; }
        public virtual DisputeRequest ErrorDisputeRequest { get; set; }
        public virtual User ModifiedByNavigation { get; set; }
        public virtual Project Project { get; set; }
        public virtual Taxonomy SourceOfMultiple { get; set; }
        public virtual Taxonomy TargetListedType { get; set; }
    }
}