// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class ProjectPublicWebsite
    {
        public int ProjectPublicWebsiteId { get; set; }
        public string WebsiteUrl { get; set; }
        public int QuotedinAnnouncements { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Guid ProjectId { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? ModifieddBy { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual User ModifieddByNavigation { get; set; }
        public virtual Project Project { get; set; }
    }
}