// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class ProjectCredDetail
    {
        public string BusinessDescription { get; set; }
        public string TargetEntityName { get; set; }
        public string ShortDescription { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public Guid ProjectId { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? ModifieddBy { get; set; }
        public int? EngagementTypeId { get; set; }
        public DateOnly? CompletedOn { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual EngagementType EngagementType { get; set; }
        public virtual User ModifieddByNavigation { get; set; }
        public virtual Project Project { get; set; }
    }
}