// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class Role
    {
        public Role()
        {
            AppRoleMenus = new HashSet<AppRoleMenu>();
            Users = new HashSet<User>();
        }

        public string Name { get; set; }
        public Guid RoleId { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? ModifiedBy { get; set; }

        public virtual User CreatedByNavigation { get; set; }
        public virtual User ModifiedByNavigation { get; set; }
        public virtual ICollection<AppRoleMenu> AppRoleMenus { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}