// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class SbuLeader
    {
        public int SbuLeaderId { get; set; }
        public int SbuId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
    }
}