// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class SbuMonthlySummaryConfig
    {
        public int SbuId { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public int? OrderId { get; set; }
    }
}