// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class ShorDescClenup
    {
        public string ProjectCode { get; set; }
        public string ClientName { get; set; }
        public string TargetEntityName { get; set; }
        public string ShortDescription { get; set; }
        public Guid? ProjectId { get; set; }
    }
}