// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class TaxonomyEngagementType
    {
        public int TaxonomyEngagementTypeId { get; set; }
        public int? TaxonomyId { get; set; }
        public int? EngagementTypeId { get; set; }
        public bool IsDeleted { get; set; }

        public virtual EngagementType EngagementType { get; set; }
        public virtual Taxonomy Taxonomy { get; set; }
    }
}