// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class TaxonomyCategory
    {
        public TaxonomyCategory()
        {
            Taxonomies = new HashSet<Taxonomy>();
        }

        public int CategoryId { get; set; }
        public string Name { get; set; }
        public bool IsDeleted { get; set; }

        public virtual ICollection<Taxonomy> Taxonomies { get; set; }
    }
}