// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class Taxonomy
    {
        public Taxonomy()
        {
            CfibProjects = new HashSet<CfibProject>();
            CredProjectRestrictedReasons = new HashSet<CredProjectRestrictedReason>();
            ProjectCredLookups = new HashSet<ProjectCredLookup>();
            ProjectCtmDetailCtmControllingTypes = new HashSet<ProjectCtmDetail>();
            ProjectCtmDetailCtmDealTypes = new HashSet<ProjectCtmDetail>();
            ProjectCtmDetailCurrencies = new HashSet<ProjectCtmDetail>();
            ProjectCtmDetailSourceOfMultiples = new HashSet<ProjectCtmDetail>();
            ProjectCtmDetailTargetListedTypes = new HashSet<ProjectCtmDetail>();
            ProjectLegalEntities = new HashSet<Project>();
            ProjectSbus = new HashSet<Project>();
            TaxonomyEngagementTypes = new HashSet<TaxonomyEngagementType>();
        }

        public int TaxonomyId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int? CategoryId { get; set; }
        public bool IsDeleted { get; set; }
        public int? ParentId { get; set; }
        public string Delemiter { get; set; }
        public string ParentPosition { get; set; }
        public string ShortName { get; set; }
        public int? OrderId { get; set; }

        public virtual TaxonomyCategory Category { get; set; }
        public virtual ICollection<CfibProject> CfibProjects { get; set; }
        public virtual ICollection<CredProjectRestrictedReason> CredProjectRestrictedReasons { get; set; }
        public virtual ICollection<ProjectCredLookup> ProjectCredLookups { get; set; }
        public virtual ICollection<ProjectCtmDetail> ProjectCtmDetailCtmControllingTypes { get; set; }
        public virtual ICollection<ProjectCtmDetail> ProjectCtmDetailCtmDealTypes { get; set; }
        public virtual ICollection<ProjectCtmDetail> ProjectCtmDetailCurrencies { get; set; }
        public virtual ICollection<ProjectCtmDetail> ProjectCtmDetailSourceOfMultiples { get; set; }
        public virtual ICollection<ProjectCtmDetail> ProjectCtmDetailTargetListedTypes { get; set; }
        public virtual ICollection<Project> ProjectLegalEntities { get; set; }
        public virtual ICollection<Project> ProjectSbus { get; set; }
        public virtual ICollection<TaxonomyEngagementType> TaxonomyEngagementTypes { get; set; }
    }
}