// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class UserType
    {
        public int UserTypid { get; set; }
        public string Name { get; set; }
    }
}