// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class VwCtmProject
    {
        public string ProjectId { get; set; }
        public string ProjectCode { get; set; }
        public string ConfirmationDate { get; set; }
        public string SubSectorName { get; set; }
        public string SectorName { get; set; }
        public string ManagerName { get; set; }
        public string PartnerName { get; set; }
        public string ProjectType { get; set; }
        public string ProjectName { get; set; }
        public string ClientName { get; set; }
    }
}