// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class VwProjectCredLookup
    {
        public Guid? ProjectId { get; set; }
        public int? TargetEntityTypeId { get; set; }
        public string TargetEntityTypeName { get; set; }
        public int? DealValueId { get; set; }
        public string DealValueName { get; set; }
        public string ClientEntityType { get; set; }
        public int? ClientEntityTypeId { get; set; }
        public string DealType { get; set; }
        public int? DealTypeId { get; set; }
        public string ParentRegion { get; set; }
        public int? ParentRegionId { get; set; }
        public string WorkRegion { get; set; }
        public int? WorkRegionId { get; set; }
        public int? NatureOfEngagementId { get; set; }
        public string NatureOfEngagement { get; set; }
        public int? ProductId { get; set; }
        public string ProductName { get; set; }
        public int? ServiceOfferingId { get; set; }
        public string ServiceOfferingName { get; set; }
        public string TransactionStatus { get; set; }
        public int? TransactionStatusId { get; set; }
        public string DiscloseEntityName { get; set; }
        public int? DiscloseEntityNameId { get; set; }
    }
}