// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class VwProjClientEntityType
    {
        public Guid? ProjectId { get; set; }
        public string ProjectCode { get; set; }
        public string ClientEntityType { get; set; }
        public int? ClientEntityTypeId { get; set; }
    }
}