// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class VwProjDownload
    {
        public DateTime? ProjectStartDate { get; set; }
        public DateOnly? ConfirmationDate { get; set; }
        public string ClientName { get; set; }
        public string ClientContactName { get; set; }
        public string ClienteMail { get; set; }
        public decimal? HoursBooked { get; set; }
        public decimal? BillingAmount { get; set; }
        public string TargetName { get; set; }
        public string SectorName { get; set; }
        public string Keywords { get; set; }
        public string ShortDescription { get; set; }
        public string DealsSbu { get; set; }
        public int? SbuId { get; set; }
        public string ManagerName { get; set; }
        public Guid? ManagerUserId { get; set; }
        public string ManagerEmail { get; set; }
        public string PartnerName { get; set; }
        public Guid? PartnerUserId { get; set; }
        public string PartnerEmail { get; set; }
        public string ProjectCode { get; set; }
        public string ProjectName { get; set; }
        public string TaskCode { get; set; }
        public string PwClegalEntity { get; set; }
        public string EngagementType { get; set; }
        public string NatureofEngagement { get; set; }
        public string NatureOfTransactionDealNatureOfWorkNonDeal { get; set; }
        public string DealValue { get; set; }
        public string Product { get; set; }
        public string TransactionStatus { get; set; }
        public string ClientEntityType { get; set; }
        public string DomicileCountryRegionOfTarget { get; set; }
        public string ClientOrClientUltimateParentEntityDomicileCountryRegion { get; set; }
        public string DiscloseEntityName { get; set; }
        public string TargetEntityType { get; set; }
        public string Status { get; set; }
        public int? StatusId { get; set; }
        public DateTime? LTB { get; set; }
        public string Debtor { get; set; }
        public string WebsiteUrl { get; set; }
        public int? QuotedinAnnouncements { get; set; }
        public DateTime? CredentialTriggerDate { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        public string Name { get; set; }
    }
}