// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class VwProjectRestrictedReason
    {
        public string Name { get; set; }
        public int? TaxonomyId { get; set; }
        public Guid? ProjectId { get; set; }
    }
}