// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class VwProjProduct
    {
        public Guid? ProjectId { get; set; }
        public string ProductName { get; set; }
        public string ServiceOfferingName { get; set; }
        public int? ProductId { get; set; }
        public int? ServiceOfferingId { get; set; }
    }
}