// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class VwProjectCred
    {
        public int? ProjectTypeId { get; set; }
        public string ClientName { get; set; }
        public string ManagerName { get; set; }
        public string PartnerName { get; set; }
        public string TargetName { get; set; }
        public string ProjectDescription { get; set; }
        public string DealsSbu { get; set; }
        public DateOnly? ConfirmationDate { get; set; }
        public string SectorName { get; set; }
        public string SubSectorName { get; set; }
        public int? SectorId { get; set; }
        public int? SubSectorId { get; set; }
        public int? TargetEntityTypeId { get; set; }
        public string TargetEntityTypeName { get; set; }
        public int? DealValueId { get; set; }
        public string DealValueName { get; set; }
    }
}