// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Deals.Domain.Models
{
    public partial class VwPvtTest
    {
        public Guid? ProjectId { get; set; }
        public string TargetEntityTypeName { get; set; }
        public string DealValueName { get; set; }
        public string ClientEntityType { get; set; }
        public string DealType { get; set; }
        public string ParentRegion { get; set; }
        public string WorkRegion { get; set; }
        public string NatureOfEngagement { get; set; }
        public string ProductName { get; set; }
        public string TransactionStatus { get; set; }
        public string DiscloseEntityName { get; set; }
    }
}