START TRANSACTION;

CREATE TABLE "DP".projectcredinfo (
    "ProjectId" integer GENERATED BY DEFAULT AS IDENTITY,
    "BusinessDescription" text NOT NULL,
    "TargetEntityName" text NOT NULL,
    "ShotDescription" text NOT NULL,
    "UUID" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "ModifiedOn" timestamp with time zone NULL,
    "CreatedBy" text NOT NULL,
    "ModifiedBy" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "StatusId" integer NOT NULL,
    CONSTRAINT "PK_projectcredinfo" PRIMARY KEY ("ProjectId")
);



CREATE TABLE "DP".projectcredlookups (
    projectcredlookupid integer GENERATED BY DEFAULT AS IDENTITY,
    "ProjectId" integer NOT NULL,
    "TaxonomyId" integer NOT NULL,
    "TaxonomyTypeId" integer NOT NULL,
    "UUID" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "ModifiedOn" timestamp with time zone NULL,
    "CreatedBy" text NOT NULL,
    "ModifiedBy" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "StatusId" integer NOT NULL,
    CONSTRAINT "PK_projectcredlookups" PRIMARY KEY (projectcredlookupid)
);

CREATE TABLE "DP".projectpublicwebsites (
    "ProjectPublicWebsiteId" integer GENERATED BY DEFAULT AS IDENTITY,
    "ProjectId" integer NOT NULL,
    "WebSite" text NOT NULL,
    "QuotedInAnnouncements" integer NOT NULL,
    "UUID" uuid NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "ModifiedOn" timestamp with time zone NULL,
    "CreatedBy" text NOT NULL,
    "ModifiedBy" text NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "StatusId" integer NOT NULL,
    CONSTRAINT "PK_projectpublicwebsites" PRIMARY KEY ("ProjectPublicWebsiteId")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20211229033953_workflow', '6.0.1');

COMMIT;

